version: '3.1'
services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '5454:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSOWRD=docker
      - POSTGRES_DB=projectdb
