version: '3.1'
services:
  db:
    build: .
    container_name: api-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSOWRD=docker
      - POSTGRES_DB=projectdb
